services:
  honeypot:
    container_name: honeypot
    platform: linux/amd64
    build:
      context: .
      dockerfile: honeypot/Dockerfile
    ports:
      - "${HONEYPOT_SSH_PORT}:2222"
      - "${HONEYPOT_TELNET_PORT}:2223"
    volumes:
      - ./var/cowrie:/home/cowrie/var
      - ./honeypot/real_honeyfs:/home/cowrie/cowrie/honeyfs

  honeypot-api:
    container_name: honeypot-api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./var:/app/var
    env_file:
      - ./.env
    environment:
      COWRIE_DB_PATH: /app/var/cowrie/cowrie.db
    ports:
      - "${HONEYPOT_API_PORT}:8000"
    command: ./app --port 8000