// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Auth struct {
	ID        int64
	Session   string
	Success   int64
	Username  string
	Password  string
	Timestamp time.Time
}

type Client struct {
	ID      int64
	Version string
}

type Download struct {
	ID        int64
	Session   string
	Timestamp time.Time
	Url       string
	Outfile   sql.NullString
	Shasum    sql.NullString
}

type Input struct {
	ID        int64
	Session   string
	Timestamp time.Time
	Realm     sql.NullString
	Success   sql.NullInt64
	Input     string
}

type Ipforward struct {
	ID        int64
	Session   string
	Timestamp time.Time
	DstIp     string
	DstPort   int64
}

type Ipforwardsdatum struct {
	ID        int64
	Session   string
	Timestamp time.Time
	DstIp     string
	DstPort   int64
	Data      string
}

type Keyfingerprint struct {
	ID          int64
	Session     string
	Username    string
	Fingerprint string
}

type Param struct {
	ID      int64
	Session string
	Arch    string
}

type Sensor struct {
	ID int64
	Ip string
}

type Session struct {
	ID        string
	Starttime time.Time
	Endtime   sql.NullTime
	Sensor    int64
	Ip        string
	Termsize  sql.NullString
	Client    sql.NullInt64
}

type Ttylog struct {
	ID      int64
	Session string
	Ttylog  string
	Size    int64
}
